# Generated by Django 5.1.2 on 2024-10-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('invoice_time', models.TimeField(auto_now_add=True)),
                ('customer_code', models.CharField(max_length=20)),
                ('po_date', models.DateField()),
                ('sales_executive', models.CharField(max_length=100)),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_address', models.TextField()),
                ('buyer_gst', models.CharField(max_length=15)),
                ('buyer_pan', models.CharField(max_length=10)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_mobile', models.CharField(max_length=15)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_address', models.TextField()),
                ('seller_gst', models.CharField(max_length=15)),
                ('seller_pan', models.CharField(max_length=10)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_mobile', models.CharField(max_length=15)),
                ('total_qty', models.PositiveIntegerField()),
                ('amount_in_words', models.CharField(max_length=200)),
                ('payment_terms', models.CharField(max_length=100)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('qr_code_data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
