# Generated by Django 5.1.2 on 2024-10-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_final', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer_code',
            new_name='Customer_Code',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_date',
            new_name='Invoice_Date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_number',
            new_name='Invoice_Number',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_time',
            new_name='Invoice_Time',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='po_date',
            new_name='PO_Date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='sales_executive',
            new_name='Sales_Executive',
        ),
    ]
